matrix:
  include:
    - language: python
      python: 3.5
      before_install:
        - sudo apt-get install -y python-software-properties debconf-utils
        - sudo add-apt-repository -y ppa:webupd8team/java
        - sudo apt-get update
        - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
        - sudo apt-get install -y oracle-java8-installer
      install:
        - sudo apt-get install neo4j=1:3.4.6
        - pip install -r requirements.txt
      script:
        - pytest components/backend/test.py components/backend/taxonomy_test.py
