matrix:
  include:
    - language: python
      python: 3.5
      before_install:
        # Workaround https://github.com/travis-ci/travis-ci/issues/7940
        - sudo rm -f /etc/boto.cfg
      install:
        - pip install -r requirements.txt
      script:
        - make test
