matrix:
  include:
    - language: python
      python: 3.5
      before_install:
        - sudo add-apt-repository ppa:webupd8team/java
        - sudo apt-get update
        - sudo apt-get install oracle-java8-installer
        - wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
        - echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
        - sudo apt-get update
      install:
        - sudo apt-get install neo4j=1:3.4.6
        - pip install -r requirements.txt
      script:
        - pytest components/backend/test.py components/backend/taxonomy_test.py
