matrix:
  include:
    - language: python
      dist: xenial
      python: 3.5
      before_install:
        # Workaround https://github.com/travis-ci/travis-ci/issues/7940
        - sudo rm -f /etc/boto.cfg
      install:
        - apt install openjdk-8-jdk
        - pip3 install pytz==2018.7
        - pip3 install -r requirements.txt
      script:
        - make test
