matrix:
  include:
    - language: python
      python: 3.5
      env:
        - OCCUBROW_ENVIRONMENT=test
      services:
        - neo4j
      before_install:
        - sudo service neo4j restart
      install:
        - pip install -r requirements.txt
      script:
        - pytest components/backend/test.py components/backend/taxonomy_test.py
