matrix:
  include:
    - language: python
      python: 3.5
      env:
        - OCCUBROW_ENVIRONMENT=test
      before_install:
        - sudo apt-get install -y python-software-properties debconf-utils
        - sudo add-apt-repository -y ppa:webupd8team/java
        - sudo apt-get update
        - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
        - sudo apt-get install -y oracle-java8-installer
        - wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
        - echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
        - sudo apt-get update
      install:
        - sudo apt-get install neo4j
        - sudo wget -O /var/lib/neo4j/plugins/apoc-3.4.0.2-all.jar https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.4.0.2/apoc-3.4.0.2-all.jar
        - sudo service neo4j restart
        - pip install -r requirements.txt
      script:
        - pytest components/backend/test.py components/backend/taxonomy_test.py
